### ISSUE TITLE
Tame case stalling (or taking a very long time)

### ISSUE THREAD

**Issue by jwj61** [cjdoris/pAdicGaloisGroup#1]
With
```
RRR<x>:=PR(pAdicField(127, 300));
ff := x^22 - 1091533853073393531649*x^2 + 6099491170974123054854612;
PGG_GaloisGroup(ff : Alg:="Tame");
```
just seems to hang, although this is a tame Galois group.

**Comment by cjdoris** [comment]
Thanks for taking a look at the code, John, and thanks for the bug report.

The issue appears to be in taking a logarithm of a finite field element in a large field (in the `TameRParameter` intrinsic), which will be slow.

I have modified the code to avoid this (b97f575d549c6a823c4515dddcf4f88a4aae8025).

Please can you try again to confirm this fixes the issue?

**Comment by jwj61** [comment]
Much faster, thanks.
